# Default configuration used when complex_editor.yml is missing.
database:
  mdb_path: "C:/ProductionData/Complexes/complexes.accdb"
links:
  bom_db_hint: "http://localhost:8080"
bridge:
  enabled: false
  base_url: "http://127.0.0.1:8765"
  auth_token: ""
  host: "0.0.0.0"
  port: 8765
  request_timeout_seconds: 15
